local su = require("someutils")
print(su)
local convert = read()
print(su.decimalToHexadecimal(convert))
print(su.decimalToBinary(convert))
sleep(1)
su.clear()
print("no input")
sleep(1)
su.clear(5, 5)
print("with input")
sleep(1)
su.clear()
print("overwriting")
for i = 1, 5 do
    su.overwriteLine(i .. "/5", 2)
    sleep(0.25)
end
su.clear()
su.centerText("this text is centered at the cursor!")
su.centerText("this text is centered to the middle!", "center")
sleep(1)
su.clear()
local menu = su.quickMenu("Test Menu", {"Option 1", "Option 2", "Option 3"})

if menu == 1 then
    print("Option 1 was selected!")
elseif menu == 2 then
    print("Option 2 was selected!")
elseif menu == 3 then
    print("Option 3 was selected!")
end

print()
print("writing hi to file")
su.quickWriteFile("test.txt", "hi")
sleep(0.1)
print("reading from file")
print(su.quickReadFile("test.txt"))
print("appending to file")
su.quickAppendFile("test.txt", "\nappended")
print("reading again")
print(su.quickReadFile("test.txt"))
fs.delete("test.txt")
sleep(1)
su.clear()
print("printing random float between 1 and 2")
print(su.randomFloat(1, 2))
print("printing the same but rounding down to 1, 3 and 5 decimals")
print(su.randomFloat(1, 2, 1))
print(su.randomFloat(1, 2, 3))
print(su.randomFloat(1, 2, 5))
print("rounding down floats")
print(1.064818)
print(su.roundDownFloat(1.064818, 3))
sleep(1)
su.clear()
print("random chances of 33.3%")
for i = 1, 10 do
    print(su.chance(33.3))
end
sleep(1)
su.clear()
print("formatting interger 123456789")
print(su.formatInt(123456789))